
path: /home/pyxis-insta/Downloads/defectflow-complete(3)/defectflow-complete (Copy)/ml/dataset
train: images/train
val: images/val
test: images/test

names:
  0: spalling
  1: stagnant_water
  2: cracked_tiles
  3: paint_peeling
